[Local]
; SQLite 数据库文件路径 (建议放在 python_embed 目录下)
db_file = ./python_embed/strm_mapping.db

[MonitorFolders]
; 本地监控strm路径，每行一个，不需要逗号、不需要序号、不需要空格
C:\box\strm.local
C:\box\strm

[WebDAV]
; Openlist WebDAV 根路径
host = http://192.168.1.1:5243/dav
user = admin
password = 1

[RefreshPaths]
; 需要主动刷新的云盘路径,每行一个(留空表示不刷新),首次启动会较久
; 此处即 openlist strm驱动中填写的路径 
; 因为目的就是触发更新钩子生成strm 还需要配置webdav_refresh_interval刷新间隔
; 警告：不建议为挂载了【本地机械硬盘】的路径开启此功能，会导致硬盘频繁唤醒和磁头损耗！
/天翼云盘家庭云30GB/番剧
/天翼云盘个人云1TB/番剧
/天翼云盘个人云30GB/番剧
/天翼云盘家庭云30GB/电影
/天翼云盘个人云1TB/电影
/天翼云盘个人云30GB/电影

[Setting]
; 操作模式: MOVE 或 DELETE 
; 作为测试,务必先使用MOVE,或使用没有删除权限的账号
action = MOVE
; 各个路径下独立的回收站文件夹名称
trash_dir_name = strm_回收站
; 主动刷新WebDAV挂载路径的间隔(分钟)。设置为 0 则关闭此功能。
; 警告：不建议为挂载了【本地机械硬盘】的路径开启此功能，会导致硬盘频繁唤醒和磁头损耗！
webdav_refresh_interval = 30
; 刷新深度：1 表示只扫根目录，2 表示扫两层，以此类推。
; 建议设为 4，足以覆盖“/挂载盘/番剧/异兽魔都/season 01/S01E01.mp4”这种结构。
webdav_refresh_depth = 4

[Log]
; 日志级别: DEBUG (记录所有细节) 或 INFO (只记录核心操作)
level = DEBUG
; 日志文件的存放路径
file = ./activity.log
; 限制日志文件最大为 2MB，超过则重置
max_size_mb = 2