[Local]
; 需要监控的本地 strm 文件夹路径,多个文件夹路径之间用英文逗号隔开
monitor_folders = C:\Users\1\Downloads\测试,C:\box\strm
; SQLite 数据库文件路径 (建议放在 python_embed 目录下)
db_file = ./python_embed/strm_mapping.db

[WebDAV]
; Openlist WebDAV 根路径
host = http://192.168.123.2:5243/dav
user = 1
password = 1

[Setting]
; 操作模式: MOVE 或 DELETE 
; 作为测试,务必先使用MOVE,或使用没有删除权限的账号
action = MOVE
; 各个路径下独立的回收站文件夹名称
trash_dir_name = strm_回收站